### ISSUE TITLE
Refactor code

### ISSUE THREAD

**Issue by AliusDieMorietur** [KirillEmets/NeuralNetwork#3]
Make unlimited number of layers. Change names [here](https://github.com/KirillEmets/NeuralNetwork/blob/42d2413b785e980eab8ae8d5cb2ad23687a6505b/src/NeuralNetwork.java#L107)

**Comment by KirillEmets** [comment]
[Made names easier to understand (I hope)](https://github.com/KirillEmets/NeuralNetwork/commit/5a85d77c6f8b5c3203a2168562c3075fe12c5af2)
[Added flixeble layers](https://github.com/KirillEmets/NeuralNetwork/commit/aa0efd4e6bc5daf6d919c31e7f7ac6341ed80234)
